### ISSUE TITLE
导入项目失败

### ISSUE THREAD

**Issue by duckAndroid** [qijitech/android-starter-kit#7]
Error:(97, 0) CreateProcess error=2, 系统找不到指定的文件。

**Comment by smartydroid** [comment]
@duckAndroid 能描述清楚一点吗，是android-starter-kit项目打开 失败吗，还是你导入library失败。

**Comment by duckAndroid** [comment]
``` java
1. git clone git@github.com:qijitech/android-starter-kit.git
2. android studio --> File Open...-->  ../android-starter-kit/bulid.gradle
3. sync gradle
4. Error:(97, 0) CreateProcess error=2, 系统找不到指定的文件。
```

<br/>
简而言之，是打开项目失败。

**Comment by smartydroid** [comment]
@duckAndroid 你的gradle版本和build tools的版本是多少，用的是什么操作系统。

最后你选择File Open 应该是选择的android-starter-kit 而不是 bulid.gradle

**Comment by duckAndroid** [comment]
@smartydroid 我的gradle和buildtools 比项目当前的要高，windows open file 你说的方式我尝试一下，不过一般的开源项目都是可以通过build.gradle打开的

**Comment by duckAndroid** [comment]
@smartydroid 
<br/>
- 使用你说的方式尝试了，open file
- 但是依然是之前的错误。
- 看你的`.gradle`文件写的比较复杂，估计是`.gradle`导致的
- 当前操作系统 `windows 10` ,`build tools 24`,`gradle:2.14`,`android studio 2.1.3`
- <b> 最好的重现方式，就是`clone`当前项目，然后看看自己能不能打开</b>

**Comment by duckAndroid** [comment]
@smartydroid 定位到的是`def versionCode = cmd.execute().text.trim()`

**Comment by Doublemine** [comment]
@duckAndroid  请将`git.exe`加入到系统的path环境变量中，gradle脚本的命令运行找到不到`git.exe`所以报错了

**Comment by wildmelon** [comment]
def cmd = 'git rev-list HEAD --all --count'
改为：
def cmd = 'cmd.exe /c git rev-list HEAD --all --count'
可能也可以

**Comment by duckAndroid** [comment]
@wildmelon 使用这种方法ok了。66666666666
@Doublemine 不知道是不是打开方式不对，使用这种方式无效。

**Comment by smartydroid** [comment]
@duckAndroid 我已经关闭了这个issue，按照@Doublemine的来就行，windows里面git需要配置环境变量
