### ISSUE TITLE
EasyRecyclerAdapter 没有 addHeaderView FooterView 之类的接口

### ISSUE THREAD

**Issue by Knight-ZXW** [qijitech/android-starter-kit#9]
如题，在使用这个框架开发，继承了 RxStarterRecyclerFragment ，遇到需要在 list尾部添加视图的情况，

**Comment by smartydroid** [comment]
@nimdanoob 我再完善一下。

**Comment by Knight-ZXW** [comment]
这个库，可以提pull request吗

**Comment by kangnixi** [comment]
@nimdanoob 可以提，非常欢迎提交 pull request
